from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any

from nonebot.adapters.onebot.v11.message import Message
from PIL import Image

import scripts.build_docs as plugin_docs_script
from src.database.core.consts import Permission
from src.lib.consts import TriggerType
from src.lib.demo_theme import (
    DEFAULT_DEMO_THEME,
    DEFAULT_IMPRESSION_COLOR,
    SENRIN_V3_THEME,
    build_demo_theme,
    get_demo_theme,
    normalize_hex_color,
)
from src.lib.i18n.runtime import tr
import src.lib.plugin_docs as plugin_docs_module
from src.lib.plugin_docs import (
    DemoImageRenderer,
    DocNode,
    DocsRenderContext,
    FeatureDoc,
    HelpDashboardSection,
    InlineTextSpan,
    ProgressiveDisclosureRenderer,
    VirtualFeatureDocSpec,
    VirtualPluginDocSpec,
    audit_demo_layout,
    build_command_layout,
    build_doc_demo_message,
    build_doc_tree,
    build_feature_copy_text,
    build_plugin_guide_copy_text,
    build_readme_docs,
    build_simple_leaf_copy_text,
    build_virtual_plugin_doc_bundle,
    create_docs_meta,
    feature_demo_help_command,
    load_doc_node,
    load_plugin_doc_bundle,
    load_representative_demo_bytes,
    load_virtual_doc_node,
    match_feature,
    render_doc_node_overview,
    render_help_dashboard,
    render_plugin_guide,
    render_static_entry,
    resolve_help_entry_shape,
    split_features_for_disclosure,
    split_inline_text_spans,
)

__all__ = [
    "DEFAULT_DEMO_THEME",
    "DEFAULT_IMPRESSION_COLOR",
    "SENRIN_V3_THEME",
    "Any",
    "BytesIO",
    "DemoImageRenderer",
    "DocNode",
    "DocsRenderContext",
    "FeatureDoc",
    "HelpDashboardSection",
    "Image",
    "InlineTextSpan",
    "Message",
    "Path",
    "Permission",
    "ProgressiveDisclosureRenderer",
    "TriggerType",
    "VirtualFeatureDocSpec",
    "VirtualPluginDocSpec",
    "audit_demo_layout",
    "build_command_layout",
    "build_demo_theme",
    "build_doc_demo_message",
    "build_doc_tree",
    "build_feature_copy_text",
    "build_plugin_guide_copy_text",
    "build_readme_docs",
    "build_simple_leaf_copy_text",
    "build_virtual_plugin_doc_bundle",
    "create_docs_meta",
    "datetime",
    "feature_demo_help_command",
    "get_demo_theme",
    "load_doc_node",
    "load_plugin_doc_bundle",
    "load_representative_demo_bytes",
    "load_virtual_doc_node",
    "match_feature",
    "normalize_hex_color",
    "plugin_docs_module",
    "plugin_docs_script",
    "render_doc_node_overview",
    "render_help_dashboard",
    "render_plugin_guide",
    "render_static_entry",
    "resolve_help_entry_shape",
    "split_features_for_disclosure",
    "split_inline_text_spans",
    "tr",
]
